export const REQUEST_USER = 'REQUEST_USER';
export type REQUEST_USER = typeof REQUEST_USER;

export const RECEIVE_USER = 'RECEIVE_USER';
export type RECEIVE_USER = typeof RECEIVE_USER;

export const RECEIVE_ERROR_USER = 'RECEIVE_ERROR_USER';
export type RECEIVE_ERROR_USER = typeof RECEIVE_ERROR_USER;

export const API = 'API';
export type API = typeof API;

export const API_START = 'API_START';
export type API_START = typeof API_START;

export const API_END = 'API_END';
export type API_END = typeof API_END;

export const ACCESS_DENIED = 'ACCESS_DENIED';
export type ACCESS_DENIED = typeof ACCESS_DENIED;

export const API_ERROR = 'API_ERROR';
export type API_ERROR = typeof API_ERROR;

export const REQUEST_ARTICLES = 'REQUEST_ARTICLES';
export type REQUEST_ARTICLES = typeof REQUEST_ARTICLES;

export const RECEIVE_ARTICLES = 'RECEIVE_ARTICLES';
export type RECEIVE_ARTICLES = typeof RECEIVE_ARTICLES;

export const SET_FAVORITE_ARTICLES = 'SET_FAVORITE_ARTICLES';
export type SET_FAVORITE_ARTICLES = typeof SET_FAVORITE_ARTICLES;

export const FOLLOW_USER = 'FOLLOW_USER';
export type FOLLOW_USER = typeof FOLLOW_USER;

export const UNFOLLOW_USER = 'UNFOLLOW_USER';
export type UNFOLLOW_USER = typeof UNFOLLOW_USER;

export const RECEIVE_ERROR_ARTICLES = 'RECEIVE_ERROR_ARTICLES';
export type RECEIVE_ERROR_ARTICLES = typeof RECEIVE_ERROR_ARTICLES;

export const ADD_ARTICLE_TO_FAVORITE = 'ADD_ARTICLE_TO_FAVORITE';
export type ADD_ARTICLE_TO_FAVORITE = typeof ADD_ARTICLE_TO_FAVORITE;

export const REMOVE_ARTICLE_FROM_FAVORITE = 'REMOVE_ARTICLE_FROM_FAVORITE';
export type REMOVE_ARTICLE_FROM_FAVORITE = typeof REMOVE_ARTICLE_FROM_FAVORITE;

export const REQUEST_ARTICLES_COMMENTS = 'REQUEST_ARTICLES_COMMENTS';
export type REQUEST_ARTICLES_COMMENTS = typeof REQUEST_ARTICLES_COMMENTS;

export const RECEIVE_ARTICLES_COMMENTS = 'RECEIVE_ARTICLES_COMMENTS';
export type RECEIVE_ARTICLES_COMMENTS = typeof RECEIVE_ARTICLES_COMMENTS;

export const RECEIVE_ERROR_ARTICLES_COMMENTS = 'RECEIVE_ERROR_ARTICLES_COMMENTS';
export type RECEIVE_ERROR_ARTICLES_COMMENTS = typeof RECEIVE_ERROR_ARTICLES_COMMENTS;

export const ADD_ARTICLES_COMMENT = 'ADD_ARTICLES_COMMENT';
export type ADD_ARTICLES_COMMENT = typeof ADD_ARTICLES_COMMENT;

export const REMOVE_ARTICLES_COMMENT = 'REMOVE_ARTICLES_COMMENT';
export type REMOVE_ARTICLES_COMMENT = typeof REMOVE_ARTICLES_COMMENT;
