export const REQUEST_USER = 'REQUEST_USER';
export type REQUEST_USER = typeof REQUEST_USER;

export const RECEIVE_USER = 'RECEIVE_USER';
export type RECEIVE_USER = typeof RECEIVE_USER;

export const RECEIVE_ERROR_USER = 'RECEIVE_ERROR_USER';
export type RECEIVE_ERROR_USER = typeof RECEIVE_ERROR_USER;

export const API = 'API';
export type API = typeof API;

export const API_START = 'API_START';
export type API_START = typeof API_START;

export const API_END = 'API_END';
export type API_END = typeof API_END;

export const ACCESS_DENIED = 'ACCESS_DENIED';
export type ACCESS_DENIED = typeof ACCESS_DENIED;

export const API_ERROR = 'API_ERROR';
export type API_ERROR = typeof API_ERROR;

export const REQUEST_ARTICLES = 'REQUEST_ARTICLES';
export type REQUEST_ARTICLES = typeof REQUEST_ARTICLES;

export const RECEIVE_ARTICLES = 'RECEIVE_ARTICLES';
export type RECEIVE_ARTICLES = typeof RECEIVE_ARTICLES;

export const RECEIVE_ERROR_ARTICLES = 'RECEIVE_ERROR_ARTICLES';
export type RECEIVE_ERROR_ARTICLES = typeof RECEIVE_ERROR_ARTICLES;

export const REQUEST_ARTICLES_COMMENTS = 'REQUEST_ARTICLES_COMMENTS';
export type REQUEST_ARTICLES_COMMENTS = typeof REQUEST_ARTICLES_COMMENTS;

export const RECEIVE_ARTICLES_COMMENTS = 'RECEIVE_ARTICLES_COMMENTS';
export type RECEIVE_ARTICLES_COMMENTS = typeof RECEIVE_ARTICLES_COMMENTS;

export const RECEIVE_ERROR_ARTICLES_COMMENTS = 'RECEIVE_ERROR_ARTICLES_COMMENTS';
export type RECEIVE_ERROR_ARTICLES_COMMENTS = typeof RECEIVE_ERROR_ARTICLES_COMMENTS;

export const ADD_ARTICLES_COMMENT = 'ADD_ARTICLES_COMMENT';
export type ADD_ARTICLES_COMMENT = typeof ADD_ARTICLES_COMMENT;

export const REMOVE_ARTICLES_COMMENT = 'REMOVE_ARTICLES_COMMENT';
export type REMOVE_ARTICLES_COMMENT = typeof REMOVE_ARTICLES_COMMENT;
